In [7]:
%run Untitled22.ipynb
!pip install xgboost

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


Importing libraries


In [50]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
import xgboost as xgb
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.metrics import confusion_matrix


## A function to calculate all mrequired metrics

In [9]:
#metrics function

def metrics(test,pred):
        precision = precision_score(test[:], pred)
        recall = recall_score(test[:], pred)
        accuracy = accuracy_score(test[:], pred)
        F1= ((2*recall*precision)/(recall+precision))
        return precision, recall, accuracy, F1

# NB model

In [10]:
# Creating the Naive Bayes classifier
nb = GaussianNB()

In [11]:
# Fit the classifier to the data
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)
NB_score = metrics(y_test,nb_pred)
NB_score
# score of the NB test
print("Scores : ", NB_score)

Scores :  (0.5948275862068966, 0.7840909090909091, 0.7471264367816092, 0.6764705882352942)


# NB with CV

In [8]:
scores = cross_val_score(nb, X, y, cv=5)

# score of the nbcv test
print("Scores : ", scores)

# print accuracy
print("Accuracy : %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Scores :  [0.9197861  0.94385027 0.91176471 0.90641711 0.93582888]
Accuracy : 0.92 (+/- 0.03)


# Random forest model

In [57]:
# training random forest classifier 
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_score  = metrics(y_test,rf_pred)



# score of the rf test
print("Scores : ", rf_score)

Scores :  (0.5507246376811594, 0.8636363636363636, 0.7164750957854407, 0.672566371681416)


# Random forest with cv

In [10]:
# random forest classifier with cross validation
# training random forest classifier 
rf = RandomForestClassifier(n_estimators=100)
scores = cross_val_score(rf, X, y, cv=5)

# score of the rfcv test
print("Scores : ", scores)

# print accuracy
print("Accuracy : %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Scores :  [0.8368984  0.88770053 0.8315508  0.81550802 0.86631016]
Accuracy : 0.85 (+/- 0.05)


## SVM model

In [15]:
# training svm classifier SVM
svm = svm.SVC(kernel='linear')
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
svm_score  = metrics(y_test,svm_pred)

# score of the svm test
print("Scores : ", svm_score)


Scores :  (0.5655737704918032, 0.7840909090909091, 0.7241379310344828, 0.6571428571428571)


# SVM with CV

In [17]:
# training SVM with cv
scores = cross_val_score(svm, X, y, cv=8)

# scores
print("Scores : ", scores)

# scrores with sd
print("Accuracy : %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Scores :  [0.7991453  0.91880342 0.86752137 0.86752137 0.88034188 0.84615385
 0.87982833 0.89270386]
Accuracy : 0.87 (+/- 0.07)


# XGB model

In [51]:
# convert format to DMatrix for XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Definig parameters for XGBoost
params = {
    "objective": "binary:logistic",
    "booster": "gbtree",
    "eval_metric": "error",
    "eta": 0.1,
    "max_depth": 10,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "seed": 123
}

# training XGBoost model
xgb = xgb.train(params, dtrain, num_boost_round=100)

# predicting on testset
xgb_pred1 = xgb.predict(dtest)
xgb_pred = [round(value) for value in xgb_pred1]




In [52]:
xgb_score = metrics(y_test,xgb_pred)
xgb_score

(0.5892857142857143, 0.75, 0.7394636015325671, 0.6599999999999999)

## Confusion matrix for binary classification

xgb

In [53]:

# Calculate the confusion matrix
cm = confusion_matrix(y_test, xgb_pred)
print("Confusion matrix:")
print(cm)

Confusion matrix:
[[127  46]
 [ 22  66]]


NB

In [54]:
# Calculate the confusion matrix
cm = confusion_matrix(y_test, nb_pred)
print("Confusion matrix:")
print(cm)

Confusion matrix:
[[126  47]
 [ 19  69]]


random forest

In [58]:
# Calculate the confusion matrix
cm = confusion_matrix(y_test, rf_pred)
print("Confusion matrix:")
print(cm)

Confusion matrix:
[[111  62]
 [ 12  76]]


svm

In [59]:
# Calculate the confusion matrix
cm = confusion_matrix(y_test, svm_pred)
print("Confusion matrix:")
print(cm)

Confusion matrix:
[[120  53]
 [ 19  69]]
